server:
  port: 9001
spring:
  application:
    name: FASTGO-PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///fastgo-product?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
mybatis-plus:
    type-aliases-package: cn.itsource.fastgo.domain,cn.itsource.fastgo.query