server:
  port: 9527
spring:
  application:
    name: FASTGO-ZUUL-GATEWAY
zuul:
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
  routes:
    plat:
      path: /plat/**
      service-id: fastgo-plat
    product:
      path: /product/**
      service-id: fastgo-product
    common:
      path: /common/**
      service-id: fastgo-common
fastgo-product: 
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 5000
fastgo-common: 
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 5000