server:
  port: 8001
spring:
  application:
    name: FASTGO-PLAT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///fastgo-plat?useSSL=false&userUnicode=true&characterEncoding=utf8
    username: root
    password: root